# Generated by Django 6.0.4 on 2026-04-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_offer', models.TextField(verbose_name='Oferta de trabajo')),
                ('cv_text', models.TextField(verbose_name='Texto del CV')),
                ('match_score', models.IntegerField(verbose_name='Score de match (0-100)')),
                ('missing_keywords', models.JSONField(verbose_name='Keywords faltantes')),
                ('suggestions', models.JSONField(verbose_name='Sugerencias de mejora')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de análisis')),
            ],
            options={
                'verbose_name': 'Resultado de análisis',
                'verbose_name_plural': 'Resultados de análisis',
                'ordering': ['-created_at'],
            },
        ),
    ]
