# Generated by Django 6.0.4 on 2026-04-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Analysis Result', 'verbose_name_plural': 'Analysis Results'},
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='ats_friendly',
            field=models.BooleanField(null=True, verbose_name='ATS Friendly'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='ats_issues',
            field=models.JSONField(default=list, verbose_name='ATS Issues'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='ats_tips',
            field=models.JSONField(default=list, verbose_name='ATS Tips'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='explanation',
            field=models.TextField(default='', verbose_name='Score Explanation'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='job_fit',
            field=models.CharField(default='', max_length=50, verbose_name='Job Fit'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='recommendation',
            field=models.CharField(default='', max_length=50, verbose_name='Application Recommendation'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Analysis Date'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='cv_text',
            field=models.TextField(verbose_name='CV Text'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='job_offer',
            field=models.TextField(verbose_name='Job Offer'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='match_score',
            field=models.IntegerField(verbose_name='Match Score (0-100)'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='missing_keywords',
            field=models.JSONField(verbose_name='Missing Keywords'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='suggestions',
            field=models.JSONField(verbose_name='Improvement Suggestions'),
        ),
    ]
